export const Questions = [
  {
    number: 1,
    type: "qcm",
    question: "Qu’est-ce que la GRH ?",
    options: [
      "A. L’ensemble des métiers permettant d’encadrer le personnel de l’entreprise",
      "B. La conciliation des intérêts de l’entreprise avec les contraintes liées au personnel",
      "C. L’ensemble des fonctions et de mesures ayant pour objectif de mobiliser et de développer les ressources du personnel",
      "D. L’ensemble des techniques de motivation du personnel",
    ],
    answers: ["C"],
  },
  {
    number: 2,
    type: "qcm",
    question: "Le rôle du responsable RH consiste à :",
    options: [
      "A. définir la politique générale de l’entreprise",
      "B. assurer le recrutement des meilleures compétences",
      "C. acquérir, développer et fidéliser le capital humain",
    ],
    answers: ["C"],
  },
  {
    number: 3,
    type: "qcm",
    question: "Dans les PME-PMI, la GRH a pour objet :",
    options: [
      "A. de définir l’organisation de l’entreprise",
      "B. d’ajuster au mieux, les savoirs, les savoirs-faire et les savoirs-être des hommes disponibles et potentiellement membres de l’entreprise, au niveau de chacune de ses fonctions",
      "C. d’investir dans l’outil de production industriel et commercial",
    ],
    answers: ["B"],
  },
  {
    number: 4,
    type: "qcu",
    question: "La GRH est :",
    options: [
      "A. une variable d’ajustement",
      "B. une variable stratégique",
      "C. une variable privilégiant la réaction plutôt que l’anticipation",
    ],
    answers: ["B"],
  },
  {
    number: 5,
    type: "qcu",
    question: "La GRH est pratique contingente :",
    options: [
      "A. parce qu’elle s’occupe des contingents de salariés",
      "B. car elle doit limiter ses contingents d’employés",
      "C. elle est influencée par des facteurs internes et externes de son environnement",
    ],
    answers: ["C"],
  },
  {
    number: 6,
    type: "qcm",
    question: "Pour les salariés, le Directeur des ressources humaines est :",
    options: [
      "A. garant de l’équité, de l’employabilité et de l’éthique",
      "B. toujours le principal actionnaire de l’entreprise",
      "C. la personne qui détermine seule, de la stratégie de l’entreprise",
    ],
    answers: ["A"],
  },
  {
    number: 7,
    type: "qcm",
    question: "Dans les PME-PMI, les contraintes de la GRH :",
    options: [
      "A. peuvent avoir un rapport avec la mondialisation et les changements technologiques",
      "B. se limitent au secteur d’activités de l’entreprise",
      "C. ne concernent pas les syndicats",
    ],
    answers: ["A"],
  },
  {
    number: 8,
    type: "qcm",
    question: "Dans les PME-PMI, les managers :",
    options: [
      "A. peuvent être un vecteur de changement des ressources humaines",
      "B. n’ont pas besoin de stratégie des ressources humaines",
      "C. ne peuvent pas s’engager dans de grandes innovations",
    ],
    answers: ["A"],
  },
  {
    number: 9,
    type: "qcu",
    question: "Les frais de personnel peuvent être considérés comme :",
    options: ["A. une charge financière.", "B. un investissement."],
    answers: ["B"],
  },
  {
    number: 10,
    type: "qcm",
    question:
      "Parmi ces différents postes, quels sont ceux qui sont rattachés à la fonction RH ?",
    options: [
      "A. Responsable Développement RH",
      "B. Directeur Administratif et Financier",
      "C. Assistant de Direction",
      "D. Responsable Formation",
      "E. Contrôleur de Gestion Sociale",
      "F. Responsable Compensation & Benefits",
      "G. Assistant juridique RH",
      "H. Consultant en recrutement",
    ],
    answers: ["A", "D", "F", "G"],
  },
  {
    number: 11,
    type: "qcu",
    question:
      "«Le service RH a décidé de confier la gestion des congés payés aux responsables opérationnels». À quel terme managérial se rapporte cette décision?",
    options: [
      "A. l'externalisation de la fonction RH",
      "B. l'internalisation de la fonction RH",
      "C. la décentralisation de la fonction RH",
      "D. la centralisation de la fonction RH",
      "E. l'outsourcing de la fonction RH",
    ],
    answers: ["C"],
  },
  {
    number: 12,
    type: "qcu",
    question: "L'ESS (Employee Self Service) fait référence à :",
    options: [
      "A. l'utilisation de l'outil informatique par le service Ressources Humaines dans ses activités quotidiennes",
      "B. l'existence d'un forum sur l'intranet d'une organisation pour répondre aux questions RH des salariés",
      "C. l'existence d'un blog pour chaque salarié via le serveur de son organisation",
      "D. la possibilité pour le salarié de gérer lui-même son dossier individuel via une application informatique",
    ],
    answers: ["D"],
  },
  {
    number: 13,
    type: "qcm",
    question:
      "Parmi ces variables, quelles sont celles qui sont susceptibles d'influencer l'activité RH de l'entreprise ?",
    options: [
      "A. la fiscalité",
      "B. l'inflation",
      "C. les budgets de l'entreprise",
      "D. les changements démographiques",
      "E. le chômage",
      "F. la structure de l'entreprise",
      "G. le dirigeant de l'entreprise",
      "H. le style de leadership",
    ],
    answers: ["A", "B", "C", "D", "E", "F", "G", "H"],
  },
  {
    number: 14,
    type: "qcu",
    question: "Quel site a modifié le travail de GRH ?",
    options: ["A. Youtube", "B. Instagram", "C. Linkedin", "D. Periscope"],
    answers: ["C"],
  },
  {
    number: 15,
    type: "qcu",
    question: "Dans une petite annonce, figurent toujours :",
    options: [
      "A. le nom et les références de l'entreprise qui recrute",
      "B. le nom et les références du candidat à l'embauche",
    ],
    answers: ["A"],
  },
];
